#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width              2
bspc config window_gap                8

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

# Border
bspc config focused_border_color   "#6c71c4"
bspc config active_border_color    "#073642"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# Autostart
#
# Disables laptop screen
xrandr --output LVDS-1 --off &

# Set background wallpaper
feh --bg-fill ~/Pictures/Wallpapers/* &

# Window settings via picom
picom -CGf &

# Execute Polybar 
polybar left -c ~/.config/polybar/config &
polybar middle -c ~/.config/polybar/config &
polybar right -c ~/.config/polybar/config &

# Dunst notification daemon
dunst 
