# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# A minimal left prompt
format = """
$all$character
"""

# move the rest of the prompt to the right
# right_format = """$all"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
