# theme = "gruvbox_dark_hard"
theme = "ayu_evolve"

[editor]
line-number = 'relative'
true-color = true
auto-completion = true
auto-format = true
auto-save = true

[editor.soft-wrap]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
"'" = "'"

[editor.lsp]
enable = true
snippets = true
display-inlay-hints = true
display-messages = true

[editor.file-picker]
hidden = false
ignore = true
git-ignore = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
# right = ["version-control"]

[keys.normal]
"C-S-down" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"C-S-up" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[keys.normal.space]
B = ["yank_main_selection_to_clipboard", ":run-shell-command tmux save-buffer - | pbcopy"]
